### ISSUE TITLE
Flatpak, Snap and Appimage packages

### ISSUE THREAD

**Issue by qarmin** [qarmin/czkawka#15]
There should be easy way to install and upgrade app on Linux

- [x]  - Flatpak
- [x]  - Appimage
- [x]  - Snap

**Comment by qarmin** [comment]
For now I have this lines in snapcraft.yml file
```
name: czkawka # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '1.4.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Czkawka - fast OS cleaner written in Rust # 79 char long summary
description: |
  Czkawka is very fast and feature rich cleaner which finds file duplicates, empty folders and files, similar images or the biggest files in selected directories. You can exclude directories by using absolute path or items(files and folders) by * wildcards.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  czkawka:
    plugin: rust
    source: https://github.com/qarmin/czkawka.git
    source-tag: 1.4.0
    build-packages:
      - libgtk-3-dev
    stage-packages:
      - libgtk-3-dev
    override-build: |
      cargo build --release --bin czkawka_gui
      ls -alR

apps:
  czkawka:
    command: target/release/czkawka_gui
```
But sadly it doesn't work now
